---
name: check HTTP requests

on:
    push:
        branches:
            - '**'

jobs:
    requests:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: 'set up'
              run: |
                sudo apt-get update
                sudo apt-get -y install curl wget
                sudo cpan App::Cpan
                sudo cpan Mojolicious
            - name: 'curl request'
              run: |
                curl --version
                curl -v https://httpbin.org/headers
            - name: 'wget request'
              run: |
                wget --version
                wget -S -O - https://httpbin.org/headers
            - name: 'mojo / morbo'
              run: |
                mojo version
                ./myapp.pl &
                mojo get http://127.0.0.1:3000
